spring:
  application:
    name: hospitalmgmt
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=hospital_mgmt
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8083
logging:
  level:
    org:
      springframework:
        security: TRACE